#!/usr/bin/env bash
set -x
git pull --rebase &&
  npm install &&
  CI=true npm test -a &&
  cat <<-'HERE'
    ___ _   _  ___ ___ ___ ___ ___
   / __| | | |/ __/ __| __/ __/ __|
   \__ \ |_| | (_| (__| _|\__ \__ \
   |___/\___/ \___\___|___|___/___/

HERE